name: Update Render Status Badge
on:
  schedule:
    - cron: '*/5 * * * *' # Update every 5 minutes
  workflow_dispatch:
jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Badge
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: npx render-status-badge > badge-url.txt
      - name: Update README
        run: |
          badge_url=$(cat badge-url.txt)
          sed -i "s|<! -- RENDER_BADGE -->.*|<!-- RENDER_BADGE -->\n[![Render Status]($badge_url)]($(cat badge-url.txt))|" README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: Update Render status badge" && git push || echo "No changes to commit" 